main: main.cpp tools.o node.o enddevice.o gateway.o networkoptimizer.o networkoptimizerrandom.o networkoptimizersprings.o networkvisualizer.o
	g++ -Wall -lGL -lGLU -lglut -o runnable main.cpp tools.o node.o enddevice.o gateway.o networkoptimizer.o networkoptimizerrandom.o networkoptimizersprings.o networkvisualizer.o

clean :
	-rm *.o $(objects) runnable